[platformio]
default_envs = esp32-024r-spotify

[env:esp32-024r-spotify]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
lib_ldf_mode = deep+
extra_scripts = pre:tools/fix_tft_button.py
lib_deps =
  bodmer/TFT_eSPI@2.5.43
  lvgl/lvgl@8.3.11
build_flags =
  -I .
  -D USER_SETUP_LOADED=1
  -D LV_CONF_INCLUDE_SIMPLE=1
  -D LV_LVGL_H_INCLUDE_SIMPLE=1
  -include tft_setup.h
