#!/usr/bin/env python3
"""Print a compact C++ header for sparse, 64x64 transparent DJ sprites.

Usage:
  python tools/pngs_to_sparse_dj_header.py > animations/dj/dj_sprites.h

The command is deliberately output-only: generated project files are applied
through the project's patch workflow, while this tool remains reproducible for
future sprite revisions.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCES = (
    ("dj_glasses", "Glasses.png"),
    ("dj_mixer_board", "Mixer bord 1.png"),
    ("dj_effect_r1", "Effects R1.png"),
    ("dj_effect_r2", "Effects R2.png"),
    ("dj_notes_l1", "Music Notes L1.png"),
    ("dj_notes_l2", "Music Notes L2.png"),
    ("dj_notes_r1", "Music Notes R1.png"),
    ("dj_notes_r2", "Music Notes R2.png"),
)


def emit_sprite(symbol: str, filename: str) -> None:
    image = Image.open(ROOT / "assets" / "User-made" / filename).convert("RGBA")
    if image.size != (64, 64):
        raise ValueError(f"{filename} must be 64x64, got {image.size}")
    pixels = [
        (x, y, red, green, blue, alpha)
        for y in range(64)
        for x in range(64)
        for red, green, blue, alpha in (image.getpixel((x, y)),)
        if alpha
    ]
    print(f"static const DjPixel {symbol}_pixels[] = {{")
    for x, y, red, green, blue, alpha in pixels:
        print(f"    {{{x}, {y}, {red}, {green}, {blue}, {alpha}}},")
    print("};")
    print(f"static const DjSprite {symbol} = {{{symbol}_pixels, {len(pixels)}}};")
    print()


def main() -> int:
    print("// Generated by tools/pngs_to_sparse_dj_header.py; do not edit by hand.")
    print("#pragma once")
    print()
    print("struct DjPixel { uint8_t x, y, r, g, b, opacity; };")
    print("struct DjSprite { const DjPixel *pixels; uint16_t pixel_count; };")
    print()
    for symbol, filename in SOURCES:
        emit_sprite(symbol, filename)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
